-- MySQL Script generated by MySQL Workbench
-- 03/05/20 11:12:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utilisateur` (
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  `dateNaissance` DATE NULL,
  `niveauSql` ENUM('DEBUTANT', 'AVANCE', 'MEDIUM') NULL,
  `description` VARCHAR(45) NULL,
  `points` INT NULL,
  PRIMARY KEY (`login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sujet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sujet` (
  `idSujet` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `picturePath` VARCHAR(45) NULL,
  `creatorLogin` VARCHAR(45) NULL,
  PRIMARY KEY (`idSujet`),
  INDEX `createur_idx` (`creatorLogin` ASC),
  CONSTRAINT `createur`
    FOREIGN KEY (`creatorLogin`)
    REFERENCES `mydb`.`Utilisateur` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Message` (
  `idMessage` INT NOT NULL,
  `content` VARCHAR(45) NULL,
  `sujetIdDestination` INT NULL,
  `senderLogin` VARCHAR(45) NULL,
  PRIMARY KEY (`idMessage`),
  INDEX `sujetDestination_idx` (`sujetIdDestination` ASC),
  INDEX `expediteur_idx` (`senderLogin` ASC),
  CONSTRAINT `expediteur`
    FOREIGN KEY (`senderLogin`)
    REFERENCES `mydb`.`Utilisateur` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sujetDestination`
    FOREIGN KEY (`sujetIdDestination`)
    REFERENCES `mydb`.`Sujet` (`idSujet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tag` (
  `nomTag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nomTag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Groupe` (
  `idGroupe` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idGroupe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SujetTag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SujetTag` (
  `sujetId` INT NOT NULL,
  `tagName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sujetId`, `tagName`),
  INDEX `tagName_idx` (`tagName` ASC),
  CONSTRAINT `sujerId`
    FOREIGN KEY (`sujetId`)
    REFERENCES `mydb`.`Sujet` (`idSujet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tagName`
    FOREIGN KEY (`tagName`)
    REFERENCES `mydb`.`Tag` (`nomTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UtilisateurGroupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UtilisateurGroupe` (
  `userLogin` VARCHAR(45) NOT NULL,
  `groupId` INT NOT NULL,
  PRIMARY KEY (`userLogin`, `groupId`),
  INDEX `groupId_idx` (`groupId` ASC),
  CONSTRAINT `userId`
    FOREIGN KEY (`userLogin`)
    REFERENCES `mydb`.`Utilisateur` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `groupId`
    FOREIGN KEY (`groupId`)
    REFERENCES `mydb`.`Groupe` (`idGroupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Favoris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Favoris` (
  `userLogin` VARCHAR(45) NOT NULL,
  `sujetId` INT NOT NULL,
  PRIMARY KEY (`userLogin`, `sujetId`),
  INDEX `sujetId_idx` (`sujetId` ASC),
  CONSTRAINT `userId`
    FOREIGN KEY (`userLogin`)
    REFERENCES `mydb`.`Utilisateur` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sujetId`
    FOREIGN KEY (`sujetId`)
    REFERENCES `mydb`.`Sujet` (`idSujet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Action` (
  `name` VARCHAR(45) NOT NULL,
  `reward` INT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UtilisateurAction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UtilisateurAction` (
  `userLogin` VARCHAR(45) NOT NULL,
  `actionName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userLogin`, `actionName`),
  INDEX `actionName_idx` (`actionName` ASC),
  CONSTRAINT `utilisateurLogin`
    FOREIGN KEY (`userLogin`)
    REFERENCES `mydb`.`Utilisateur` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `actionName`
    FOREIGN KEY (`actionName`)
    REFERENCES `mydb`.`Action` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Specialite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Specialite` (
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Competence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Competence` (
  `userLogin` VARCHAR(45) NOT NULL,
  `specialiteName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userLogin`, `specialiteName`),
  INDEX `specialiteName_idx` (`specialiteName` ASC),
  CONSTRAINT `userLogin`
    FOREIGN KEY (`userLogin`)
    REFERENCES `mydb`.`Utilisateur` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `specialiteName`
    FOREIGN KEY (`specialiteName`)
    REFERENCES `mydb`.`Specialite` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Invitation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Invitation` (
  `userLogin` VARCHAR(45) NOT NULL,
  `groupeId` INT NOT NULL,
  PRIMARY KEY (`userLogin`, `groupeId`),
  INDEX `groupeId_idx` (`groupeId` ASC),
  CONSTRAINT `userLogin`
    FOREIGN KEY (`userLogin`)
    REFERENCES `mydb`.`Utilisateur` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `groupeId`
    FOREIGN KEY (`groupeId`)
    REFERENCES `mydb`.`Groupe` (`idGroupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
